Combine slides into units

diff --git a/.github/workflows/build-textbook.yml b/.github/workflows/build-textbook.yml
--- a/.github/workflows/build-textbook.yml
+++ b/.github/workflows/build-textbook.yml
@@ -57,34 +57,11 @@ jobs:
           mkdir -p dist
           pip install -r requirements.txt
 
-          # Initalize the output markdown file
-          output_file="../source/slides.md"
-          echo "# Slides" > "$output_file"
+          # TODO: Add "no-overwrite" mode so we can skip nicely formatted slides
+          python build_slides.py "../source/index.md" --output "./dist/" --as-toc --quiet || {
+              echo "Failed to convert ../source/index.md" >&2
+          }
 
-          # Construct the base URL dynamically
-          org_name="${GITHUB_REPOSITORY%/*}"
-          repo_name="${GITHUB_REPOSITORY##*/}"
-          base_url="https://$org_name.github.io/$repo_name/assets/slides"
-
-          # Iterate over all of the markdown files in ../source/text/ directories
-          # for file in ../source/text/**/*.md; do
-          find ../source/text/ -type f -name "*.md" | sort -V | while read -r file; do
-            # Extract the base name of the file (e.g., "conditionals.md")
-            base_name=$(basename "$file")
-            # Extract the directory name of the file (e.g., "1-typescript")
-            dir_name=$(dirname "$file" | xargs -I {} basename {})
-            # Construct the output filename (e.g., "1-typescript-conditionals.pptx")
-            output_name="${dir_name}-${base_name%.md}.pptx"
-            # Convert the markdown file to a powerpoint file
-            python build_slides.py "$file" --output "./dist/$output_name" --quiet || {
-              echo "Failed to convert $file" >&2
-              continue
-            }
-            # Construct the url
-            url="$base_url/$output_name"
-            # Append the filename and URL to the markdown file
-            echo "* [$output_name]($url)" >> "$output_file"
-          done
           cd ../
       - name: Copy slides
         run: |
